import { Link, useLocation } from 'react-router-dom';
import { ArrowRight, Zap, Users, Heart, DollarSign, BookOpen, Award } from 'lucide-react';

const Landing = () => {
  const location = useLocation();
  const message = location.state?.message;
  const features = [
    {
      icon: BookOpen,
      title: 'AI-Powered Learning',
      description: 'Get personalized skill roadmaps generated by advanced AI to match your goals and learning style.'
    },
    {
      icon: DollarSign,
      title: 'Micro-Scholarships',
      description: 'Earn real rewards for completing milestones. Every achievement brings you closer to financial success.'
    },
    {
      icon: Users,
      title: 'Peer Mentorship',
      description: 'Connect with mentors and peers who share your passion. Learn together, grow together.'
    },
    {
      icon: Heart,
      title: 'Wellness Support',
      description: 'Maintain balance with AI-powered wellness check-ins and mental health resources.'
    },
    {
      icon: Award,
      title: 'Verified Portfolio',
      description: 'Build a credible portfolio of completed projects and skills that employers trust.'
    },
    {
      icon: Zap,
      title: 'Impact Tracking',
      description: 'See your real impact on the community and track your journey to success.'
    }
  ];

  const testimonials = [
    {
      name: 'Sarah Johnson',
      role: 'Full-Stack Developer',
      avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?w=150',
      quote: 'SkillBridge helped me transition from retail to tech in just 6 months. The mentorship and structured learning path made all the difference.'
    },
    {
      name: 'Miguel Santos',
      role: 'Data Analyst',
      avatar: 'https://images.pexels.com/photos/1040880/pexels-photo-1040880.jpeg?w=150',
      quote: 'The micro-scholarships motivated me to complete every milestone. I earned $400 while learning Python and landed my dream job!'
    },
    {
      name: 'Aisha Patel',
      role: 'UX Designer',
      avatar: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?w=150',
      quote: 'The wellness companion kept me balanced during intense learning periods. Mental health support in education is revolutionary.'
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 to-teal-50">
      {message && (
        <div className="bg-green-100 border-l-4 border-green-500 text-green-700 p-4 text-center" role="alert">
          <p className="font-bold">Success</p>
          <p>{message}</p>
        </div>
      )}


      {/* Hero Section */}
      <section className="relative overflow-hidden">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24">
          <div className="text-center">

            <h1 className="text-4xl md:text-6xl font-bold text-gray-900 mb-6">
              Bridge your skills.<br />
              <span className="text-green-600">Build your future.</span><br />
              <span className="text-teal-600">Shape your community.</span>
            </h1>

            <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
              The first AI-powered platform that combines personalized learning, micro-scholarships, 
              peer mentorship, and wellness support to empower youth aged 15-29.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center mb-12">
              <Link
                to="/auth"
                className="bg-gradient-to-r from-green-600 to-teal-600 text-white px-8 py-4 rounded-lg font-semibold text-lg hover:from-green-700 hover:to-teal-700 transition-all transform hover:scale-105 flex items-center justify-center space-x-2"
              >
                <span>Start Your Journey</span>
                <ArrowRight className="w-5 h-5" />
              </Link>
              <button className="bg-white text-gray-900 px-8 py-4 rounded-lg font-semibold text-lg border-2 border-gray-200 hover:border-green-300 transition-colors">
                Watch Demo
              </button>
            </div>

            {/* Stats */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-2xl mx-auto">
              <div className="text-center">
                <div className="text-3xl font-bold text-green-600 mb-2">10,000+</div>
                <div className="text-gray-600">Active Learners</div>
              </div>
              <div className="text-center">
                <div className="text-3xl font-bold text-teal-600 mb-2">$2.5M+</div>
                <div className="text-gray-600">Scholarships Distributed</div>
              </div>
              <div className="text-center">
                <div className="text-3xl font-bold text-yellow-500 mb-2">95%</div>
                <div className="text-gray-600">Success Rate</div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              Everything you need to succeed
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Our comprehensive platform combines cutting-edge AI with human connection 
              to create the ultimate learning experience.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <div key={index} className="bg-gray-50 p-8 rounded-xl hover:bg-gray-100 transition-colors">
                <div className="w-12 h-12 bg-gradient-to-r from-green-600 to-teal-600 rounded-lg flex items-center justify-center mb-4">
                  <feature.icon className="w-6 h-6 text-white" />
                </div>
                <h3 className="text-xl font-semibold text-gray-900 mb-3">{feature.title}</h3>
                <p className="text-gray-600">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="py-20 bg-gradient-to-r from-green-600 to-teal-600">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
              Success Stories
            </h2>
            <p className="text-xl text-green-100 max-w-2xl mx-auto">
              Real people, real transformations, real impact on communities worldwide.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {testimonials.map((testimonial, index) => (
              <div key={index} className="bg-white p-8 rounded-xl">
                <div className="flex items-center mb-4">
                  <img 
                    src={testimonial.avatar} 
                    alt={testimonial.name}
                    className="w-12 h-12 rounded-full object-cover mr-4"
                  />
                  <div>
                    <h4 className="font-semibold text-gray-900">{testimonial.name}</h4>
                    <p className="text-sm text-gray-600">{testimonial.role}</p>
                  </div>
                </div>
                <blockquote className="text-gray-700 italic">
                  "{testimonial.quote}"
                </blockquote>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gray-900">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-6">
            Ready to transform your future?
          </h2>
          <p className="text-xl text-gray-300 mb-8">
            Join thousands of learners who are already building their dream careers 
            with SkillBridge AI. Your journey starts today.
          </p>
          <Link
            to="/auth"
            className="bg-gradient-to-r from-green-600 to-teal-600 text-white px-8 py-4 rounded-lg font-semibold text-lg hover:from-green-700 hover:to-teal-700 transition-all transform hover:scale-105 inline-flex items-center space-x-2"
          >
            <span>Get Started Free</span>
            <ArrowRight className="w-5 h-5" />
          </Link>
        </div>
      </section>

    </div>
  );
};

export default Landing;